# Generated by Django 5.2.7 on 2025-10-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(max_length=100, verbose_name='Nama Lengkap'),
        ),
    ]
